---
title: "New3_Completion"
author: "Serina"
date: "2023-07-26"
output: html_document
---
#library
```{r}
rm(list=ls())
library(sf)
library(terra)
library(readr)
library(dplyr)
library(tidyr)
library(adehabitatLT)
library(geosphere)
library(sf)
library(ggplot2)
```

#data
```{r}
csv_files <- list.files(path = "~/Documents/yodalab/data/middle_data/Added/No2_wrontrip_removed/", 
                        pattern = "\\.csv$", full.names = TRUE)
for (file in csv_files) {
  var_name <- tools::file_path_sans_ext(basename(file))
  assign(var_name, read_csv(file), envir = .GlobalEnv)
}
```

#Resampled to 5-minute intervals using the adehabitatLT
```{r}
#Define
###########################################################
window          <- 3600*24#[sec]
sampling_min    <- 5
sampling_time   <- 60*sampling_min#[sec]
#max_point          <- window/sampling
speed_threshold <- 10*1000/3600 #Threshold to difine flying/Water
time_zone_no <- 54
###########################################################
file_path <- "~/Documents/yodalab/data/middle_data/Added/No2_wrontrip_removed/"
out_data <-tibble()
files <- list.files(file_path, pattern = "*.csv$", full.names = TRUE)
###########################################################################
for(id_file in 1: length(files)){
###########################################################################
data_r      <- read_csv(files[id_file])
id_list <-unique(data_r$ID)
n_id <-   length(id_list)
###############################################################################
for(id_bird in 1:n_id ){
###############################################################################
  print(paste(id_bird,":",id_list[[id_bird]]))
  data <- filter(data_r, ID==id_list[id_bird])
　data <- data.frame(ID = data$ID, Time = data$time, Lon = data$lon, Lat = data$lat, Ring = data$id, Label = data$label, Sex = data$sex, Age = data$age, Trip_ID = data$Trip_ID)
　data <- distinct(data, Time, .keep_all = TRUE)

############################################################
# Resampling by the defined time (sampling_interval)
# Coordinates are temporarily converted from WGS 84 (lat/lon) to UTM Zone 54N (x/y in meters) for distance and speed calculations, as adehabitatLT requires a flat coordinate system
############################################################
    ##Use NCAT tool by NOAA
    ##https://www.ngs.noaa.gov/NCAT/
     llcoord  <- SpatialPoints(cbind(data$Lon,data$Lat), proj4string=CRS("+proj=longlat +datum=WGS84"))
     utmcoord <- spTransform(llcoord, CRS(paste("+proj=utm +zone=",time_zone_no," +ellps=WGS84",sep="")))
      x <- attr(utmcoord,"coords")[,1]
      y <- attr(utmcoord,"coords")[,2]
     xy <- data.frame(x,y)

    track <-  as.ltraj(xy = xy, date = data$Time, id = data$ID)
    track <- redisltraj(track, sampling_time , type="time")
    print(track)
        track <- data.frame(Time = track[[1]]$date,
                           x = track[[1]]$x,
                           y = track[[1]]$y,
                          dt = track[[1]]$dt,
                        dist = track[[1]]$dist,
                       Angle = track[[1]]$abs.angle)

    track <- mutate(track, Speed = dist/dt,
                           ID = rep(id_list[[id_bird]],nrow(track)))
######################################################
#Obs 1:observation　NA:no observation
######################################################
Obs <- rep(NA,nrow(track))
for(i_obs in 1:nrow(track)){
  deficit <- abs(track[i_obs,]$Time-data$Time) %>% min() %>% as.numeric(units="secs")
  if(deficit <=sampling_time){
Obs[i_obs]  <- 1
  }
}
track <- mutate(track, Obs)
###########################################################
# Flight_State: Flying:1　Water:0
# If the speed is more than speed_threshold: Flying, if not:Water
###########################################################

track <- mutate(track, Flight_State  = as.numeric(track$Speed > speed_threshold))
out_data <- rbind(out_data, track)
  }
#Output
file_name <- gsub(".csv","",basename(files[[id_file]]))
output_path <- "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/"
write_csv(out_data, paste0(output_path, file_name, ".csv"))
assign(paste0(file_name, "_resampled"), out_data)
out_data <- tibble()
}
```

#Read the file again
```{r}
rm(list=ls())
csv_files <- list.files(path = "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/",
                        pattern = "\\.csv$", full.names = TRUE)
for (file in csv_files) {
  var_name <- tools::file_path_sans_ext(basename(file))
  assign(paste0(var_name, "_resampled"), read_csv(file), envir = .GlobalEnv)
}
```

##Fix the deleted data
#Fix1: individual info
```{r}
#Extract the individual ID from the trip ID: retrieve the portion "2021_09083730" from "2021_09083730_1_trip"
#Create a year_label column in d2013~d2022 and use it to match and merge individual information

###Step1. read individual info, add the column "year_id"
csv_files <- list.files(path = "~/Documents/yodalab/data/first_data/individual_cleaned/", 
                        pattern = "\\.csv$", full.names = TRUE)
csv_files %>%
  purrr::walk(~{
    var_name <- tools::file_path_sans_ext(basename(.))
    df <- read_csv(.) %>%
      mutate(year_id = paste0(year, "_", foot))
    assign(var_name, df, envir = .GlobalEnv)
  })


###Step2. extract year)id from resampled data
years <- 2013:2022
for (year in years) {
  input_df_name <- paste0("d", year, "_tracked")
  output_df_name <- paste0("longtrip", year, "_resampled")
  input_df <- get(input_df_name)
  output_df <- get(output_df_name)
output_df <- output_df %>% 
  separate(ID, into = c("part1", "part2", "part3", "part4"), sep = "_", remove = FALSE)
output_df <- output_df %>% 
  unite("year_id", part1:part2, sep = "_", remove = FALSE) %>% 
  dplyr::select(-part1:-part4)
  combined <- left_join(output_df, input_df, by = c("year_id" = "year_id"))
  assign(paste0(output_df_name), combined, envir = .GlobalEnv)
  print(sum(is.na(combined$id)))
}
```

#Fix2: add lon lat Nest_Distance
```{r}
#Convert coordinates from UTM Zone 54N (meters) back to WGS 84 (latitude/longitude)
year_list <- c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022)

for (year in year_list) {
  file_name <- paste0("longtrip", year, "_resampled")
  data <- get(file_name)
  data_sf <- st_as_sf(data, coords = c("x", "y"), crs = 32654) # UTM Zone 54N
  data_ll <- st_transform(data_sf, crs = 4326) # WGS 84
  data_latlon <- data.frame(st_coordinates(data_ll))
  colnames(data_latlon) <- c("lon", "lat")
  location_nest <- c(141.5576031, 40.5386062)
  data_latlon$Nest_Distance <- distGeo(location_nest, cbind(data_latlon$lon, data_latlon$lat))
  data_with_latlon <- cbind(data, data_latlon)

  output_file_name <- paste0("longtrip", year, "_all.csv")
  output_path <- "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/fixed/"
  file_path <- file.path(output_path, output_file_name)

  write.csv(data_with_latlon, file_path, row.names = FALSE)
}
```

#Read the file again
```{r}
rm(list=ls())
csv_files <- list.files(path = "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/fixed/", 
                        pattern = "\\.csv$", full.names = TRUE)
for (file in csv_files) {
  var_name <- tools::file_path_sans_ext(basename(file))
  assign(var_name, read_csv(file), envir = .GlobalEnv)
}
```

#Fill Nest_Distance of the last row
```{r}
year_list <- c("longtrip2013_all", "longtrip2014_all", "longtrip2015_all", "longtrip2016_all", "longtrip2017_all", "longtrip2018_all", "longtrip2019_all", "longtrip2020_all", "longtrip2021_all", "longtrip2022_all")

for (year in year_list) {
  # get the data frame
  df <- get(year)
  df_grouped <- df %>%
    group_by(ID) %>%
    summarise(last_nest_distance = last(Nest_Distance))
  assign(paste0("last_nest_distance_", year), df_grouped)
}
all_years_data <- data.frame()
for (year in year_list) {
  df <- get(paste0("last_nest_distance_", year))
  df$year <- year
  all_years_data <- bind_rows(all_years_data, df)
}
print(all_years_data)

max(all_years_data$last_nest_distance)
#[1] 8611.673
```

#Make the column name consistant
```{r}
year_list <- c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022)

for (year in year_list) {
  file_name <- paste0("longtrip", year, "_all")
  data <- get(file_name)
  data <- data %>% dplyr::select(-Obs, -dt, -year_id)
  colnames(data)[1:18] <- c("time","x","y","step_length", "step_angle", "step_speed","ID","flight_state", "label", "foot","age", "sex","logger","type", "year", "lon", "lat", "Nest_Distance")
  data <- data[, c("time","lon", "lat","x","y","ID", "label","foot","age", "sex","logger","type", "year", "Nest_Distance", "flight_state", "step_length", "step_angle", "step_speed")]
  output_file_name <- paste0("longtrip", year, "_all.csv")
  output_path <- "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/fixed/"
  file_path <- file.path(output_path, output_file_name)
  write_csv(data, file_path)
}
```

#Read the file again
```{r}
rm(list=ls())
csv_files <- list.files(path = "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/fixed/", 
                        pattern = "\\.csv$", full.names = TRUE)
for (file in csv_files) {
  var_name <- tools::file_path_sans_ext(basename(file))
  assign(var_name, read_csv(file), envir = .GlobalEnv)
}
```

#Check the speed
```{r}
year_list <- c("longtrip2013_all","longtrip2014_all","longtrip2015_all","longtrip2016_all","longtrip2017_all","longtrip2018_all","longtrip2019_all","longtrip2020_all","longtrip2021_all","longtrip2022_all")

for (year in year_list) {
data_out_all <- data.frame()
data0 <- get(year)
id_list <- unique(data0$ID)
n_id <- length(id_list)

for(i in 1:n_id) {
data <- data0%>%
  filter(ID == id_list[i])
data_out <- data.frame()

n <- nrow(data)

Lon <- data$lon
Lat <- data$lat

location1 <- cbind(Lon[1:n-1], Lat[1:n-1])
location2 <- cbind(Lon[2:n], Lat[2:n])
Step_Length <- distGeo(location1, location2)

data$time <- as.POSIXct(data$time, format="%Y/%m/%d, %H:%M:%S")
dt <- data$time %>%
  diff() %>%
  as.numeric(unit=("secs"))
speed <- Step_Length/dt

Step_Length <- c(Step_Length, NA)
check_dt <- c(dt, NA)
check_speed <- c(speed, NA)*3.6
data_out <- mutate(data, check_speed, check_dt)
data_out_all <- bind_rows(data_out_all, data_out)
}
assign(paste0("speed", year), data_out_all)
}
```

#Speed range in each year
```{r}
# データフレームのリストを作成
df_names <- paste0("speedlongtrip", 2013:2022, "_all")

# 各データフレームに対して処理を行う
for (df_name in df_names) {
  # データフレームを取得
  df <- get(df_name)
  
  # speed列がNAまたは無限でない行をフィルタリング
  df <- df[complete.cases(df$check_speed) & !is.infinite(df$check_speed), ]
  
  # フィルタリング後のデータフレームを元の名前で保存
  assign(df_name, df, envir = .GlobalEnv)
  
  # speedの範囲を表示
  print(paste0(df_name, " speed range: ", range(df$check_speed, na.rm = TRUE)))
}
```

#Visualize each individuals
```{r}
out_place <- "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/Trip_plot/"
year_list <- c("longtrip2013_all", "longtrip2014_all", "longtrip2015_all", "longtrip2016_all", "longtrip2017_all", "longtrip2018_all", "longtrip2019_all", "longtrip2020_all", "longtrip2021_all", "longtrip2022_all")

pal <- c("#3B9AB2", "#56A6BA", "#71B3C2", "#9EBE91", "#D1C74C",
         "#E8C520", "#E4B80E", "#E29E00", "#EA5C00", "#F21A00")

for (year in year_list) {
  final_data <- get(year)
  id_list <- unique(final_data$ID)
  n_id <- length(id_list)
  
  for(i in 1:n_id){
    data1 <- final_data %>%
      filter(ID==id_list[i])
    
    fig<- ggplot(data1, aes(x=lon, y=lat, colour = Nest_Distance))+geom_point(size=0.5)+ scale_color_gradientn(colors = pal)+theme_light()
    
    ggsave(file = paste(out_place, id_list[i],".png", sep=""), plot=fig)
  }
}
```

#Output
```{r}
in_dataframes <- c("speedlongtrip2013_all","speedlongtrip2014_all","speedlongtrip2015_all","speedlongtrip2016_all","speedlongtrip2017_all","speedlongtrip2018_all","speedlongtrip2019_all","speedlongtrip2020_all","speedlongtrip2021_all","speedlongtrip2022_all")
out_dataframes <- c("GPS2013","GPS2014","GPS2015","GPS2016","GPS2017","GPS2018","GPS2019","GPS2020","GPS2021","GPS2022")

out_dir <- "~/Documents/yodalab/data/middle_data/Added/No3_5min_resampled/fixed/"

for(i in seq_along(in_dataframes)) {
  data <- get(in_dataframes[i])
  out_filename <- paste0(out_dir, out_dataframes[i], ".csv")
  write_csv(data, out_filename)
}
```