---
title: "Visualize model"
author: "YusukeGoto, Serina"
date: "2024-04-10"
output: html_document
---
#library
```{r}
library(rstan)
library(ggplot2)
library(tidyverse)
library(here)
library(extrafont)
library(cowplot)
library(tibble)
library(rstan)
```

#Fig4
Environmental effects included (day = 1, distance = median)
```{r}
#fit <- readRDS(here("~/Documents/yodalab/data/model/StanResult_dist_forpaper.rds"))

all_sea_data <- read_csv(here("~/Documents/yodalab/data/model/all_sea_data_wind.csv"))
all_sea_data <- all_sea_data %>%
  mutate(year_foot = paste(year, foot, sep = "_"))

if(abs(mean(all_sea_data$Nest_Distance, na.rm = TRUE)) > 1000) {
  all_sea_data$Nest_Distance <- as.vector(scale(all_sea_data$Nest_Distance))
}

extract_params_with_env <- function(fit, param_name) {
  param <- rstan::extract(fit, pars = param_name)[[param_name]]
  mean_param <- apply(param, 2, mean)
  lower_ci_95 <- apply(param, 2, quantile, probs = 0.025)
  upper_ci_95 <- apply(param, 2, quantile, probs = 0.975)
  lower_ci_75 <- apply(param, 2, quantile, probs = 0.125)
  upper_ci_75 <- apply(param, 2, quantile, probs = 0.875)
  
  data.frame(
    mean = mean_param, 
    lower_ci_95 = lower_ci_95, 
    upper_ci_95 = upper_ci_95,
    lower_ci_75 = lower_ci_75, 
    upper_ci_75 = upper_ci_75
  )
}

a_post <- extract_params_with_env(fit, "a")
s_a_post <- extract_params_with_env(fit, "s_a")
s_a_Trip_post <- extract_params_with_env(fit, "s_a_Trip")

c_params <- rstan::extract(fit, pars = "c")$c
c2_params <- rstan::extract(fit, pars = "c2")$c2
e_params <- rstan::extract(fit, pars = "e")$e

c_mean <- mean(c_params)
c2_mean <- mean(c2_params)
e_mean <- mean(e_params)

nest_distance_median <- median(all_sea_data$Nest_Distance, na.rm = TRUE)
day_night_value <- 1  # Day

environmental_effect <- c_mean * nest_distance_median + 
                       c2_mean * nest_distance_median^2 + 
                       e_mean * day_night_value

unique_age_mapping <- all_sea_data %>%
  dplyr::select(year_foot, age) %>%
  distinct() 

df_age <- data.frame(Age = unique_age_mapping$age)
min_age <- min(df_age$Age)
max_age <- max(df_age$Age)

data_a_age_only <- tibble(
  Age = min_age:max_age,
  Mean = a_post$mean,
  LowerCI95 = a_post$lower_ci_95,
  UpperCI95 = a_post$upper_ci_95,
  LowerCI75 = a_post$lower_ci_75,
  UpperCI75 = a_post$upper_ci_75,
  Type = "Age effect only"
)

data_a_with_env <- tibble(
  Age = min_age:max_age,
  Mean = a_post$mean + environmental_effect,
  LowerCI95 = a_post$lower_ci_95 + environmental_effect,
  UpperCI95 = a_post$upper_ci_95 + environmental_effect,
  LowerCI75 = a_post$lower_ci_75 + environmental_effect,
  UpperCI75 = a_post$upper_ci_75 + environmental_effect,
  Type = "With environmental effects"
)

data_a_comparison <- rbind(data_a_age_only, data_a_with_env)

data_s_a <- tibble(
  Age = min_age:max_age,
  Mean = s_a_post$mean,
  LowerCI95 = s_a_post$lower_ci_95,
  UpperCI95 = s_a_post$upper_ci_95,
  LowerCI75 = s_a_post$lower_ci_75,
  UpperCI75 = s_a_post$upper_ci_75,
  var = rep("SD_among_Ind", nrow(s_a_post))
)

data_s_a_Trip <- tibble(
  Age = min_age:max_age,
  Mean = s_a_Trip_post$mean,
  LowerCI95 = s_a_Trip_post$lower_ci_95,
  UpperCI95 = s_a_Trip_post$upper_ci_95,
  LowerCI75 = s_a_Trip_post$lower_ci_75,
  UpperCI75 = s_a_Trip_post$upper_ci_75,
  var = rep("SD_within_Ind", nrow(s_a_Trip_post))
)

plot_df <- rbind(data_s_a, data_s_a_Trip)

common_theme <- theme_bw(base_family = "Arial") +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black", linewidth = 0.2),
    axis.ticks = element_line(colour = "black", linewidth = 0.2),
    plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm"),
    text = element_text(size = 24),
    axis.text = element_text(size = 24),
    axis.title = element_text(size = 24),
    plot.title = element_text(size = 24)
  )

x_min <- min(df_age$Age) - 0.5
x_max <- max(df_age$Age) + 0.5

common_x_axis <- scale_x_continuous(
  limits = c(x_min, x_max),
  breaks = seq(ceiling(x_min), floor(x_max), by = 2),
  expand = c(0, 0)
)

p_h <- ggplot(df_age) +
  geom_histogram(aes(x = Age), fill = "steelblue4", binwidth = 1) +
  common_x_axis +
  common_theme +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  ylab("Individual number")

p_a_env <- ggplot(data_a_with_env, aes(x = Age, y = Mean)) +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.8, linetype = "dashed") +
  geom_point(size = 4) +
  geom_line() +
  geom_ribbon(aes(ymin = LowerCI95, ymax = UpperCI95), alpha = 0.2, fill = "lightskyblue") +
  geom_ribbon(aes(ymin = LowerCI75, ymax = UpperCI75), alpha = 0.4, fill = "steelblue") +
  common_x_axis +
  common_theme +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank()) +
  ylab("Degree of drift") 

p_s <- ggplot(plot_df, aes(x = Age, y = Mean, group = var, color = var)) +
  geom_point(size = 4) +
  geom_line() +
  geom_ribbon(aes(ymin = LowerCI95, ymax = UpperCI95, fill = var), alpha = 0.2, color = NA) +
  geom_ribbon(aes(ymin = LowerCI75, ymax = UpperCI75, fill = var), alpha = 0.4, color = NA) +
  scale_color_manual(values = c("SD_among_Ind" = "darkorange", "SD_within_Ind" = "yellowgreen")) +
  scale_fill_manual(values = c("SD_among_Ind" = "darkorange", "SD_within_Ind" = "yellowgreen")) +
  common_x_axis +
  common_theme +
  theme(legend.position = "none") +
  ylab("SD of degree of drift") +
  xlab("Age")

p_comb_env_only <- plot_grid(p_h, p_a_env, p_s, 
                             ncol = 1, rel_heights = c(0.2, 0.4, 0.4), align = "v")

ggsave(here("~/Documents/yodalab/data/model/Figure4_environmental_effects.png"), 
       plot = p_comb_env_only, width = 10, height = 16, dpi = 600)
```

