---
title: "New3_Resampling_adehabitatLT"
output: html_document
date: "2023-07-26"
---

#library
```{r}
rm(list = ls())
library(sf)
library(terra)
library(readr)
library(dplyr)
library(tidyr)
library(adehabitatLT)
library(geosphere)
library(ggplot2)
library(purrr)
library(tibble)
```
#data
```{r}
rm(list=ls())

#If you are using multiple file in GitHub input_files folder
input_dir <- "~/Documents/yodalab/paper/JAB/data/input/"

input_files <- list.files(
  input_dir,
  pattern = "\\.csv$",
  full.names = TRUE
)

data <- input_files %>%
  purrr::map(~ readr::read_csv(.x, show_col_types = FALSE)) %>%
  dplyr::bind_rows()

#If you are using single file including all years
#data <- read_csv("~/Documents/yodalab/paper/JAB/data/input_data.csv")
```

#Resampling
by adehabitatLT package
```{r}
#Define the criteria
###################################################
sampling_min <- 5 #[min]
sampling_time <- 60*sampling_min #[sec]
speed_threshold <- 10*1000/3600 #[10km/hr], threshold to define flying/water
time_zone_no <- 54
###################################################

out_data <- tibble()
id_list <- unique(data$ID)
n_id <- length(id_list)

  for(id_bird in 1:n_id) {
    print(paste(id_bird, ":", id_list[[id_bird]]))
    data_one <- filter(data, ID == id_list[id_bird])
    
    data_one <- data.frame(
  ID = data_one$ID,
  Time = data_one$time,
  Lon = data_one$lon,
  Lat = data_one$lat,
  Age = data_one$age,
  Year = data_one$year
  )
    data_one <- distinct(data_one, Time, .keep_all = TRUE)
#convert from WGS84 (lat/lon) to UTM Zone 54N (x/y in meters)    
    llcoord <- SpatialPoints(cbind(data_one$Lon, data_one$Lat), proj4string = CRS("+proj=longlat +datum=WGS84"))
    utmcoord <- spTransform(llcoord, CRS(paste("+proj=utm +zone=", time_zone_no, " +ellps=WGS84", sep="")))
    x <- attr(utmcoord, "coords")[,1]
    y <- attr(utmcoord, "coords")[,2]
    xy <- data.frame(x,y)
    track <- as.ltraj(xy = xy, date = data_one$Time, id = data_one$ID)
    track <- redisltraj(track, sampling_time, type="time")
    track <- data.frame(Time = track[[1]]$date,
                        x = track[[1]]$x,
                        y = track[[1]]$y,
                        dt = track[[1]]$dt,
                        dist = track[[1]]$dist,
                        Angle = track[[1]]$abs.angle)
    track <- mutate(
      track,
      Speed = dist / dt,
      ID = id_list[[id_bird]],
      year = unique(data_one$Year),
      age = unique(data_one$Age)
  )
    
    Obs <- rep(NA, nrow(track))
    for(i_obs in 1:nrow(track)){
      deficit <- abs(track[i_obs, ]$Time - data_one$Time) %>% min() %>% as.numeric(units = "secs")
      if(deficit <= sampling_time){
        Obs[i_obs] <- 1
      }
    }
    track <- mutate(track, Obs)
    #1: Flying, 0:Water
    track <- mutate(track, Flight_State = as.numeric(track$Speed > speed_threshold))
    out_data <- rbind(out_data, track)
  }
  #Output
write_csv(out_data, "~/Documents/yodalab/paper/JAB/data/not_for_upload/data_resampled.csv")
```

#Fix the deleted data (lon, lat)
add lon lat Nest_Distance
```{r}
processed_data <- read_csv(
  "~/Documents/yodalab/paper/JAB/data/not_for_upload/data_resampled.csv",
  show_col_types = FALSE
)

# Convert UTM Zone 54N (x, y) back to WGS84 (lon, lat)
data_sf <- st_as_sf(
  processed_data,
  coords = c("x", "y"),
  crs = 32654
)

data_ll <- st_transform(
  data_sf,
  crs = 4326
)

data_latlon <- data.frame(
  st_coordinates(data_ll)
)

colnames(data_latlon) <- c("lon", "lat")


# Calculate distance from nest
location_nest <- c(141.5576031, 40.5386062)

data_latlon$Nest_Distance <- distGeo(
  location_nest,
  cbind(data_latlon$lon, data_latlon$lat)
)

# Add lon, lat, Nest_Distance
processed_data <- cbind(
  st_drop_geometry(data_ll),
  data_latlon
)
```

#Check if it comes back to nest and change column name + Save
```{r}
# Fill/check Nest_Distance of the last row for each ID
last_nest_distance <- processed_data %>%
  group_by(ID) %>%
  summarise(
    last_nest_distance = last(Nest_Distance),
    .groups = "drop"
  )

print(last_nest_distance)

max(last_nest_distance$last_nest_distance, na.rm = TRUE)
#[1] 8611.673


# Recalculate step speed for checking, following the old pipeline.
# This uses each point and the next point within each trip.
# Therefore, the last row of each trip has no next point and gets NA.
processed_data <- processed_data %>%
  group_by(ID) %>%
  arrange(Time, .by_group = TRUE) %>%
  group_modify(~ {
    df <- .x
    
    n <- nrow(df)
    
    if (n < 2) {
      df$check_speed <- NA_real_
      df$check_dt <- NA_real_
      return(df)
    }
    
    location1 <- cbind(df$lon[1:(n - 1)], df$lat[1:(n - 1)])
    location2 <- cbind(df$lon[2:n], df$lat[2:n])
    
    Step_Length <- geosphere::distGeo(location1, location2)
    
    dt <- diff(df$Time) %>%
      as.numeric(units = "secs")
    
    speed <- Step_Length / dt
    
    df$check_speed <- c(speed, NA_real_) * 3.6
    df$check_dt <- c(dt, NA_real_)
    
    df
  }) %>%
  ungroup()

# Remove rows where check_speed cannot be calculated.
processed_data <- processed_data %>%
  filter(
    complete.cases(check_speed),
    !is.infinite(check_speed)
  )


processed_data <- processed_data %>%
  dplyr::select(-Obs, -dt) %>%
  dplyr::rename(
    time = Time,
    step_length = dist,
    step_angle = Angle,
    step_speed = Speed,
    flight_state = Flight_State
  )

write_csv(
  processed_data,
  "~/Documents/yodalab/paper/JAB/data/not_for_upload/data_resampled_all.csv"
)
```

#Visualize each individuals
```{r}
out_place <- "~/Documents/yodalab/paper/JAB/data/not_for_upload/trip/"
pal <- c("#3B9AB2", "#56A6BA", "#71B3C2", "#9EBE91", "#D1C74C",
         "#E8C520", "#E4B80E", "#E29E00", "#EA5C00", "#F21A00")

  final_data <- processed_data
  id_list <- unique(final_data$ID)
  n_id <- length(id_list)
  
  for(i in 1:n_id){
    data1 <- final_data %>%
      filter(ID==id_list[i])
    
    fig<- ggplot(data1, aes(x=lon, y=lat, colour = Nest_Distance))+geom_point(size=0.5)+ scale_color_gradientn(colors = pal)+theme_light()
    
    ggsave(file = paste(out_place, id_list[i],".png", sep=""), plot=fig)
  }
```

